# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quoted_by',
            new_name='author',
        ),
    ]
